Port 3000
Listen 127.0.0.1
Timeout 600
Allow 127.0.0.1
MaxClients 1000





upstream http decencyawowo2021_gmail_com-dc:5N7xPfHxnfJBg5X@us-east.gw.rayobyte.com:8000 "tr189.surfe.pro"
upstream http decencyawowo2021_gmail_com-dc:5N7xPfHxnfJBg5X@us-east.gw.rayobyte.com:8000 "rt58.surfe.pro"
upstream http decencyawowo2021_gmail_com-dc:5N7xPfHxnfJBg5X@us-east.gw.rayobyte.com:8000 "surfe.pro"
