Port 3000
Listen 127.0.0.1
Timeout 600
Allow 127.0.0.1
MaxClients 1000





upstream http R99wYUje:YcDDaGSb@gateway.aluvia.io:8080 "tr189.surfe.pro"
upstream http R99wYUje:YcDDaGSb@gateway.aluvia.io:8080 "rt58.surfe.pro"
upstream http R99wYUje:YcDDaGSb@gateway.aluvia.io:8080 "surfe.pro"
